# **Food Wastage Analysis**

# **Libraries Used:**

In [29]:
import pandas as pd

# **Data:**

In [3]:
food_df = pd.read_csv('data/food_listings_data.csv')
food_df

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
0,1,Bread,43,3/17/2025,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,3/24/2025,791,Grocery Store,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,3/28/2025,478,Catering Service,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,3/16/2025,930,Restaurant,Kellytown,Vegan,Lunch
4,5,Soup,14,3/19/2025,279,Restaurant,Garciaport,Vegan,Dinner
...,...,...,...,...,...,...,...,...,...
995,996,Fish,15,3/30/2025,467,Catering Service,Phillipsfort,Vegan,Breakfast
996,997,Fish,22,3/18/2025,35,Grocery Store,Andersonmouth,Vegetarian,Breakfast
997,998,Fruits,6,3/22/2025,444,Restaurant,New Billy,Non-Vegetarian,Dinner
998,999,Pasta,15,3/30/2025,702,Supermarket,Lake Mistyton,Non-Vegetarian,Lunch
999,1000,Salad,18,3/19/2025,155,Supermarket,Charlesview,Non-Vegetarian,Dinner

In [4]:
provider_df = pd.read_csv('data/providers_data.csv')
provider_df

,Provider_ID,Name,Type,Address,City,Contact
0,1,Gonzales-Cochran,Supermarket,"74347 Christopher Extensions\nAndreamouth, OK ...",New Jessica,+1-600-220-0480
1,2,"Nielsen, Johnson and Fuller",Grocery Store,"91228 Hanson Stream\nWelchtown, OR 27136",East Sheena,+1-925-283-8901x6297
2,3,Miller-Black,Supermarket,"561 Martinez Point Suite 507\nGuzmanchester, W...",Lake Jesusview,001-517-295-2206
3,4,"Clark, Prince and Williams",Grocery Store,"467 Bell Trail Suite 409\nPort Jesus, IA 61188",Mendezmouth,556.944.8935x401
4,5,Coleman-Farley,Grocery Store,"078 Matthew Creek Apt. 319\nSaraborough, MA 53978",Valentineside,193.714.6577
...,...,...,...,...,...,...
995,996,"Vasquez, Ruiz and Flowers",Restaurant,"84308 Justin Stravenue\nNew Amberside, NE 53447",Williamview,+1-319-378-7627x0682
996,997,Garza-Williams,Catering Service,"08864 Figueroa Radial Suite 948\nJennaberg, AZ...",East Rossside,001-924-441-3963x746
997,998,Novak Group,Grocery Store,"934 Zachary Run\nMelissamouth, WY 02729",Joshuastad,(903)642-1969x3300
998,999,Moody Ltd,Grocery Store,"17580 Ernest Hills\nLake Michaelmouth, OR 56416",Stevenchester,637.300.3664x4880
999,1000,Jenkins-Brooks,Restaurant,"53390 Evans Rapids Suite 982\nLake Meghan, MO ...",Brendantown,266-324-3458x95775

In [5]:
receiver_df = pd.read_csv('data/receivers_data.csv')
receiver_df

,Receiver_ID,Name,Type,City,Contact
0,1,Donald Gomez,Shelter,Port Carlburgh,(955)922-5295
1,2,Laurie Ramos,Individual,Lewisburgh,761.042.1570
2,3,Ashley Mckee,NGO,South Randalltown,691-023-0094x856
3,4,Erika Rose,NGO,South Shaneville,8296491111
4,5,John Romero,Individual,Bakerport,067.491.0154
...,...,...,...,...,...
995,996,Matthew Curtis,Shelter,Lanechester,127-889-4442x1289
996,997,Amanda Cain,NGO,New Steven,+1-001-491-5601x5316
997,998,Theodore Briggs,Individual,South Sandra,930-609-9442x5031
998,999,Cheyenne Ramsey,NGO,Lake Jeffery,001-326-320-4816x15300
999,1000,April Miller,Shelter,Shelbychester,894-873-2652x23999

In [6]:
claims_df = pd.read_csv('data/claims_data.csv')
claims_df

     Claim_ID  Food_ID  Receiver_ID     Status        Timestamp
0           1      164          908    Pending    3/5/2025 5:26
1           2      353          391  Cancelled  3/11/2025 10:24
2           3      626          492  Completed   3/21/2025 0:59
3           4       61          933  Cancelled    3/4/2025 9:08
4           5      345          229    Pending  3/14/2025 15:17
..        ...      ...          ...        ...              ...
995       996      855          211  Completed  3/13/2025 19:40
996       997      980          746  Cancelled  3/17/2025 22:04
997       998      832          967  Cancelled  3/13/2025 18:00
998       999      917           90  Completed   3/1/2025 15:31
999      1000      596          950  Cancelled  3/13/2025 12:51

[1000 rows x 5 columns]

# **All Data:**

In [7]:
all_df = {"Food": food_df, "Provider": provider_df, "Receiver": receiver_df, "Claims": claims_df}

Nulls or Duplicates:

In [8]:
for name, df in all_df.items():
    print(name)
    print(df.isna().sum())
    print(df.duplicated().sum())
    print()

Food
Food_ID          0
Food_Name        0
Quantity         0
Expiry_Date      0
Provider_ID      0
Provider_Type    0
Location         0
Food_Type        0
Meal_Type        0
dtype: int64
0

Provider
Provider_ID    0
Name           0
Type           0
Address        0
City           0
Contact        0
dtype: int64
0

Receiver
Receiver_ID    0
Name           0
Type           0
City           0
Contact        0
dtype: int64
0

Claims
Claim_ID       0
Food_ID        0
Receiver_ID    0
Status         0
Timestamp      0
dtype: int64
0

* No Nulls or Duplicated values present.

Similar Columns:

In [9]:
for name, df in all_df.items():
    print(f"Common ID columns for {name} Dataset")
    for other_name, other_df in all_df.items():
        if other_name != name:
            common_cols = set(df.columns) & set(other_df.columns)
            id_cols = [col for col in common_cols if col.endswith("_ID")]
            if id_cols:
                print(f"With {other_name}: {id_cols}")
    print()

Common ID columns for Food Dataset
With Provider: ['Provider_ID']
With Claims: ['Food_ID']

Common ID columns for Provider Dataset
With Food: ['Provider_ID']

Common ID columns for Receiver Dataset
With Claims: ['Receiver_ID']

Common ID columns for Claims Dataset
With Food: ['Food_ID']
With Receiver: ['Receiver_ID']

# **Food DF:**

In [10]:
food_df

,Food_ID,Food_Name,Quantity,Expiry_Date,Provider_ID,Provider_Type,Location,Food_Type,Meal_Type
0,1,Bread,43,3/17/2025,110,Grocery Store,South Kellyville,Non-Vegetarian,Breakfast
1,2,Soup,22,3/24/2025,791,Grocery Store,West James,Non-Vegetarian,Dinner
2,3,Fruits,46,3/28/2025,478,Catering Service,Lake Regina,Vegan,Breakfast
3,4,Fruits,15,3/16/2025,930,Restaurant,Kellytown,Vegan,Lunch
4,5,Soup,14,3/19/2025,279,Restaurant,Garciaport,Vegan,Dinner
...,...,...,...,...,...,...,...,...,...
995,996,Fish,15,3/30/2025,467,Catering Service,Phillipsfort,Vegan,Breakfast
996,997,Fish,22,3/18/2025,35,Grocery Store,Andersonmouth,Vegetarian,Breakfast
997,998,Fruits,6,3/22/2025,444,Restaurant,New Billy,Non-Vegetarian,Dinner
998,999,Pasta,15,3/30/2025,702,Supermarket,Lake Mistyton,Non-Vegetarian,Lunch
999,1000,Salad,18,3/19/2025,155,Supermarket,Charlesview,Non-Vegetarian,Dinner

Unique Values:

In [28]:
for i in food_df.select_dtypes('object').columns:
    if i != 'Expiry_Date':
        print(food_df[i].value_counts())
        print()

Food_Name
Rice          114
Soup          111
Salad         105
Chicken       103
Dairy         103
Pasta         102
Bread          98
Fish           92
Vegetables     91
Fruits         81
Name: count, dtype: int64

Provider_Type
Supermarket         267
Restaurant          258
Grocery Store       243
Catering Service    232
Name: count, dtype: int64

Location
New Carol          6
South Kathryn      6
East Angela        5
Perezport          5
Jimmyberg          5
                  ..
North Steven       1
Deborahland        1
Nolanmouth         1
South Johnshire    1
Garciaport         1
Name: count, Length: 624, dtype: int64

Food_Type
Vegetarian        336
Vegan             334
Non-Vegetarian    330
Name: count, dtype: int64

Meal_Type
Breakfast    254
Snacks       253
Lunch        248
Dinner       245
Name: count, dtype: int64